### ISSUE TITLE
Handling non-standard file extensions

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-stream-handler#45]
**Feature description**
We are currently initializing the ExoPlayer with `MediaItem mediaItem = MediaItem.fromUri(videoUri);`. This has the downside that the URI needs to have a standard file extension, in order for the corresponding media source to be automatically created. In cases in which an MPD is missing `.mpd` in the filename, this can cause an issue. 

In situations in which we know the content type because it is defined in the ServiceAccessInformation (for instance `application/dash+xml` for DASH) we can provide this information to the Exoplayer. As a consequence, a non-existent file extensions will not cause an error.

````
// Use the explicit MIME type to build an HLS media item.
MediaItem mediaItem = new MediaItem.Builder()
    .setUri(hlsUri)
    .setMimeType(MimeTypes.APPLICATION_M3U8)
    .build();
````

See: https://exoplayer.dev/media-items.html

**Comment by dsilhavy** [comment]
Addressed in #46

**Comment by rjb1000** [comment]
Testing on Monday by @jonniebeeb of the latest version (from @dsilhavy's development branch) suggests that this fix might  not be working as expected. See attached [log3 2023-08-14.txt](https://github.com/5G-MAG/rt-5gms-media-stream-handler/files/12368417/log3.2023-08-14.txt).

The version number from the log is as follows:
> ExoPlayerImpl: Init ea9a8db [AndroidXMedia3/1.0.2] [lynx, Pixel 7a, Google, 33]

And we are seeing errors of the following sort:
```
08-14 14:11:46.726 23239 23239 E EventLogger: internalError [eventTime=23.44, mediaPos=0.00, window=0, period=0, loadError
08-14 14:11:46.726 23239 23239 E EventLogger:   androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
08-14 14:11:46.726 23239 23239 E EventLogger:       at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
08-14 14:11:46.726 23239 23239 E EventLogger:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
08-14 14:11:46.726 23239 23239 E EventLogger:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
08-14 14:11:46.726 23239 23239 E EventLogger:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-14 14:11:46.726 23239 23239 E EventLogger:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-14 14:11:46.726 23239 23239 E EventLogger:       at java.lang.Thread.run(Thread.java:1012)
08-14 14:11:46.726 23239 23239 E EventLogger: ]
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal: Playback error
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:652)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:622)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-14 14:11:46.727 23239 23272 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1012)
08-14 14:11:46.732 23239 23239 E EventLogger: playerFailed [eventTime=23.45, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED
08-14 14:11:46.732 23239 23239 E EventLogger:   androidx.media3.exoplayer.ExoPlaybackException: Source error
08-14 14:11:46.732 23239 23239 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:652)
08-14 14:11:46.732 23239 23239 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:622)
08-14 14:11:46.732 23239 23239 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-14 14:11:46.732 23239 23239 E EventLogger:       at android.os.Looper.loopOnce(Looper.java:201)
08-14 14:11:46.732 23239 23239 E EventLogger:       at android.os.Looper.loop(Looper.java:288)
08-14 14:11:46.732 23239 23239 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-14 14:11:46.732 23239 23239 E EventLogger:   Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
08-14 14:11:46.732 23239 23239 E EventLogger:       at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
08-14 14:11:46.732 23239 23239 E EventLogger:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
08-14 14:11:46.732 23239 23239 E EventLogger:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
08-14 14:11:46.732 23239 23239 E EventLogger:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-14 14:11:46.732 23239 23239 E EventLogger:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-14 14:11:46.732 23239 23239 E EventLogger:       at java.lang.Thread.run(Thread.java:1012)
08-14 14:11:46.732 23239 23239 E EventLogger: ]
08-14 14:11:46.732 23239 23239 D ExoPlayer: Error
```

**Comment by dsilhavy** [comment]
@rjb1000 @jonniebeeb I was unable to reproduce this in my local setup:

### M8 
After starting the 5GMSd Aware Application I select the following entry from my `m8.js`:

````js
{
  provisioningSessionId: 8,
  name: 'Local to nosuffix'
}
````

### M5
The Service Access Information at M5 returns the following for provisioningSessionId `8`:

````javascript
8: {
    provisioningSessionId: 8,
        provisioningSessionType: 'DOWNLINK',
        streamingAccess: {
        entryPoints: [
            {
                locator: baseURL+ ':3003/redirect/nosuffix',
                contentType: 'application/dash+xml',
                profiles: [
                    'urn:mpeg:dash:profile:isoff-live:2011'
                ]
            }
        ]
    }
},
````

In this case, the `locator` URL has no `.mpd` file extension. Note that the `contentType` needs to be set to `application/dash+xm` otherwise the feature implemented in this issue is not working. 

### Requesting the resource
Now the client requests the MPD at `baseURL+ ':3003/redirect/nosuffix'` which returns:

````js
router.get('/nosuffix', function (req, res, next) {
    res.writeHead(302, {
        'Content-Type': '',
        'Location': 'http://192.168.2.1:3333/steering-content/bbb/alpha/fivegmag-nosuffix'
    });
    res.end();
});
````

We are creating a redirect to another location `http://192.168.2.1:3333/steering-content/bbb/alpha/fivegmag-nosuffix` again with no file extension.

### Result
Playback starts as expected

### Next steps
1. Can you make sure that you have the correct `contentType` specified in your ServiceAccessInformation.
2. Can you paste your ServiceAccessInformation in this ticket
3. Do your media segments have a file extension e.g. `mp4`, `m4s` or something similar?

**Comment by davidjwbbc** [comment]
Alternatively you could use:
```json
{
    "aspId": "BBC-RD-5G",
    "appId": "BBCRD5GTestbed",
    "streams": {
	"ed": {
	    "name": "M5: Elephant's Dream [AMS]",
	    "ingestURL": "http://amssamples.streaming.mediaservices.windows.net/b6822ec8-5c2b-4ae0-a851-fd46a78294e9/ElephantsDream.ism/",
	    "distributionConfigurations": [
		{
		    "entryPoint": {
			"relativePath": "manifest(format=mpd-time-csf)",
			"contentType": "application/dash+xml",
			"profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
		    }
		},
		{
                    "entryPoint": {
                        "relativePath": "manifest(format=m3u8-aapl-v3)",
                        "contentType": "application/vnd.apple.mpegurl"
                    }
		}
	    ]
	},
	"ld": {
	    "name": "M5: Llama Drama [AMS]",
	    "ingestURL": "http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/",
	    "distributionConfigurations": [
		{
		    "entryPoint": {
			"relativePath": "manifest(format=mpd-time-csf)",
			"contentType": "application/dash+xml",
			"profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
		    }
		},
		{
                    "entryPoint": {
                        "relativePath": "manifest(format=m3u8-aapl-v3)",
                        "contentType": "application/vnd.apple.mpegurl"
                    }
		}
	    ]
	},
	"vodamp": {
	    "name": "M5: AMP Demo Streams [AMS]",
	    "ingestURL": "http://amssamples.streaming.mediaservices.windows.net/",
	    "distributionConfigurations": [
		    {}
	    ]
	}
    },
    "vodMedia": [
	{
	    "name": "M8: Elephant's Dream [AMS]",
	    "stream": "vodamp",
	    "entryPoints": [
		{
                    "relativePath": "b6822ec8-5c2b-4ae0-a851-fd46a78294e9/ElephantsDream.ism/manifest(format=mpd-time-csf)",
                    "contentType": "application/dash+xml",
                    "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                },
		{
                    "relativePath": "b6822ec8-5c2b-4ae0-a851-fd46a78294e9/ElephantsDream.ism/manifest(format=m3u8-aapl-v3)",
                    "contentType": "application/vnd.apple.mpegurl"
                }
	    ]
	},
	{
	    "name": "M8: Llama Drama [AMS]",
	    "stream": "vodamp",
            "entryPoints": [
                {
                    "relativePath": "634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=mpd-time-csf)",
                    "contentType": "application/dash+xml",
                    "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                },
                {
                    "relativePath": "634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl-v3)",
                    "contentType": "application/vnd.apple.mpegurl"
                }
            ]
	}
    ]
}
```

**Comment by davidjwbbc** [comment]
Done some more testing today and we've had the app successfully play back both versions (M8 entry point and M5 SAI entry point). We'd had a few minor issues with the M5 interface (always returned 404 due to a configuration issue), the DNS (DNS server wasn't running for our standalone demo) and some AS directory permissions. Having tidied those up we could debug, but were still seeing the same issue so I've done a full rebuild and redeploy of the AF, the App and its libraries and the Media Session Handler Service. Since the rebuild it's been working as expected, so it's possible that something somewhere had gotten out of sync.

I'd like to test against our other AS/AF server to make sure the redeploy works there too.

**Comment by dsilhavy** [comment]
Thanks for testing @davidjwbbc . I leave this issue open until you did the final test.

**Comment by rjb1000** [comment]
> I've done a full rebuild and redeploy of the AF, the App and its libraries and the Media Session Handler Service. Since the rebuild it's been working as expected, so it's possible that something somewhere had gotten out of sync.

We suspect the libraries were either not recompiled or not redeployed to Maven, so an old library was being packaged up.

I wonder if it's possible to spit out a library version number in the application logs to help with future debugging?

**Comment by dsilhavy** [comment]
> > I've done a full rebuild and redeploy of the AF, the App and its libraries and the Media Session Handler Service. Since the rebuild it's been working as expected, so it's possible that something somewhere had gotten out of sync.
> 
> We suspect the libraries were either not recompiled or not redeployed to Maven, so an old library was being packaged up.
> 
> I wonder if it's possible to spit out a library version number in the application logs to help with future debugging?

Addressed in 
* https://github.com/5G-MAG/rt-5gms-application/pull/24
* https://github.com/5G-MAG/rt-5gms-media-session-handler/pull/34

**Comment by dsilhavy** [comment]
@rjb1000 @davidjwbbc : Forgot this in the call today. Can we close this issue?

**Comment by rjb1000** [comment]
Yes, we can close, @dsilhavy. Thank you.
